config/routes.rb
Rails.application.routes.draw do
  resources :player_scores
  resources :players
  resources :teams
  resources :users
  resources :leagues
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  get '/scrap/:tourId/:matchId', to: 'application#scrap'
  get '/score/:tourId/:matchId', to: 'application#scrapScoreCard'
  get '/leages/:leagueId/team', to: 'application#addPlayers'
  get '/players/user/:userId', to: 'players#user'
  get '/players/user/:playerId/:userId', to: 'players#update_user'
  get '/players/search/:name', to: 'players#search'
  get '/user/destroy/:id', to: 'application#destroyUser'

end

app/models/player_score.rb
class PlayerScore < ApplicationRecord
  belongs_to :player
end

app/controllers/player_scores_controller.rb
class PlayerScoresController < ApplicationController
  before_action only: [:show, :edit, :update, :destroy]

  # GET /player_scores
  # GET /player_scores.json
  def index
    @player_scores = PlayerScore.all
  end

  # GET /player_scores/1
  # GET /player_scores/1.json
  def show
      @player_scores = PlayerScore.where(player_id: params[:id])
  end

  # GET /player_scores/new
  def new
    @player_score = PlayerScore.new
  end

  # GET /player_scores/1/edit
  def edit
  end

  # POST /player_scores
  # POST /player_scores.json
  def create
    @player_score = PlayerScore.new(player_score_params)

    respond_to do |format|
      if @player_score.save
        format.html { redirect_to @player_score, notice: 'Player score was successfully created.' }
        format.json { render :show, status: :created, location: @player_score }
      else
        format.html { render :new }
        format.json { render json: @player_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /player_scores/1
  # PATCH/PUT /player_scores/1.json
  def update
    respond_to do |format|
      if @player_score.update(player_score_params)
        format.html { redirect_to @player_score, notice: 'Player score was successfully updated.' }
        format.json { render :show, status: :ok, location: @player_score }
      else
        format.html { render :edit }
        format.json { render json: @player_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_scores/1
  # DELETE /player_scores/1.json
  def destroy
    @player_score.destroy
    respond_to do |format|
      format.html { redirect_to player_scores_url, notice: 'Player score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_score
      @player_score = PlayerScore.where(player_id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_score_params
      params.require(:player_score).permit(:player, :Starting_11)
    end
end

app/helpers/player_scores_helper.rb
module PlayerScoresHelper
end

app/views/player_scores/_form.html.erb
<%= form_with(model: player_score, local: true) do |form| %>
  <% if player_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player_score.errors.count, "error") %> prohibited this player_score from being saved:</h2>

      <ul>
      <% player_score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :player_id %>
    <%= form.text_field :player_id, id: :player_score_player_id %>
  </div>

  <div class="field">
    <%= form.label :starting_11 %>
    <%= form.text_field :starting_11, id: :player_score_starting_11 %>
  </div>

  <div class="field">
    <%= form.label :runs %>
    <%= form.text_field :runs, id: :player_score_runs %>
  </div>

  <div class="field">
    <%= form.label :fours %>
    <%= form.text_field :fours, id: :player_score_fours %>
  </div>

  <div class="field">
    <%= form.label :sixes %>
    <%= form.text_field :sixes, id: :player_score_sixes %>
  </div>

  <div class="field">
    <%= form.label :str %>
    <%= form.text_field :str, id: :player_score_str %>
  </div>

  <div class="field">
    <%= form.label :centuries %>
    <%= form.text_field :centuries, id: :player_score_centuries %>
  </div>

  <div class="field">
    <%= form.label :duck %>
    <%= form.text_field :duck, id: :player_score_duck %>
  </div>

  <div class="field">
    <%= form.label :wkts %>
    <%= form.text_field :wkts, id: :player_score_wkts %>
  </div>

  <div class="field">
    <%= form.label :maiden %>
    <%= form.text_field :maiden, id: :player_score_maiden %>
  </div>

  <div class="field">
    <%= form.label :er %>
    <%= form.text_field :er, id: :player_score_er %>
  </div>

  <div class="field">
    <%= form.label :bonus %>
    <%= form.text_field :bonus, id: :player_score_bonus %>
  </div>

  <div class="field">
    <%= form.label :catches %>
    <%= form.text_field :catches, id: :player_score_catches %>
  </div>

  <div class="field">
    <%= form.label :runout %>
    <%= form.text_field :runout, id: :player_score_runout %>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.text_field :total, id: :player_score_total %>
  </div>

  <div class="field">
    <%= form.label :match_id %>
    <%= form.number_field :match_id, id: :player_score_match_id %>
  </div>

  <div class="field">
    <%= form.label :match %>
    <%= form.text_field :match, id: :player_score_match %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/player_scores/edit.html.erb
<h1>Editing Player Score</h1>

<%= render 'form', player_score: @player_score %>

<%= link_to 'Show', @player_score %> |
<%= link_to 'Back', player_scores_path %>

app/views/player_scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Player Scores</h1>

<table>
  <thead>
    <tr>
      <th>Player</th>
      <th>Starting 11</th>
      <th>Runs</th>
      <th>Fours</th>
      <th>Sixes</th>
      <th>Str</th>
      <th>Centuries</th>
      <th>Duck</th>
      <th>Wkts</th>
      <th>Maiden</th>
      <th>Er</th>
      <th>Bonus</th>
      <th>Catches</th>
      <th>Runout</th>
      <th>Total</th>
      <th>Match</th>
      <th>Match</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @player_scores.each do |player_score| %>
      <tr>
        <td><%= player_score.player.name %></td>
        <td><%= player_score.starting_11 %></td>
        <td><%= player_score.runs %></td>
        <td><%= player_score.fours %></td>
        <td><%= player_score.sixes %></td>
        <td><%= player_score.str %></td>
        <td><%= player_score.centuries %></td>
        <td><%= player_score.duck %></td>
        <td><%= player_score.wkts %></td>
        <td><%= player_score.maiden %></td>
        <td><%= player_score.er %></td>
        <td><%= player_score.bonus %></td>
        <td><%= player_score.catches %></td>
        <td><%= player_score.runout %></td>
        <td><%= player_score.total %></td>
        <td><%= player_score.match_id %></td>
        <td><%= player_score.match %></td>
        <!-- <td><%= link_to 'Show', player_score %></td>
        <td><%= link_to 'Edit', edit_player_score_path(player_score) %></td>
        <td><%= link_to 'Destroy', player_score, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player Score', new_player_score_path %>

app/views/player_scores/new.html.erb
<h1>New Player Score</h1>

<%= render 'form', player_score: @player_score %>

<%= link_to 'Back', player_scores_path %>

app/views/player_scores/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Player Scores</h1>

<table>
  <thead>
    <tr>
      <th>Player</th>
      <th>Starting 11</th>
      <th>Runs</th>
      <th>Fours</th>
      <th>Sixes</th>
      <th>Str</th>
      <th>Centuries</th>
      <th>Duck</th>
      <th>Wkts</th>
      <th>Maiden</th>
      <th>Er</th>
      <th>Bonus</th>
      <th>Catches</th>
      <th>Runout</th>
      <th>Total</th>
      <th>Match</th>
      <th>Match</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @player_scores.each do |player_score| %>
      <tr>
        <td><%= player_score.player.name %></td>
        <td><%= player_score.starting_11 %></td>
        <td><%= player_score.runs %></td>
        <td><%= player_score.fours %></td>
        <td><%= player_score.sixes %></td>
        <td><%= player_score.str %></td>
        <td><%= player_score.centuries %></td>
        <td><%= player_score.duck %></td>
        <td><%= player_score.wkts %></td>
        <td><%= player_score.maiden %></td>
        <td><%= player_score.er %></td>
        <td><%= player_score.bonus %></td>
        <td><%= player_score.catches %></td>
        <td><%= player_score.runout %></td>
        <td><%= player_score.total %></td>
        <td><%= player_score.match_id %></td>
        <td><%= player_score.match %></td>
        <!-- <td><%= link_to 'Show', player_score %></td>
        <td><%= link_to 'Edit', edit_player_score_path(player_score) %></td>
        <td><%= link_to 'Destroy', player_score, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Player Score', new_player_score_path %> -->