config/routes.rb
Rails.application.routes.draw do
  resources :player_scores
  resources :players
  resources :teams
  resources :users
  resources :leagues
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  get '/scrap/:tourId/:matchId', to: 'application#scrap'
  get '/score/:tourId/:matchId', to: 'application#scrapScoreCard'
  get '/leages/:leagueId/team', to: 'application#addPlayers'
  get '/players/user/:userId', to: 'players#user'
  get '/players/user/:playerId/:userId', to: 'players#update_user'
  get '/players/search/:name', to: 'players#search'
  get '/user/destroy/:id', to: 'application#destroyUser'

end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_many :player_scores
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.order("players.id ASC").all
  end


  def search
    player =  Player.find_by(name: params[:name])
    puts player
    id = nil
    if(player != nil)
      id = player.id
    end
    puts id
    render plain: id
  end
  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user
    @players = TeamPlayer.where(user_id: params[:userId])
    @user = User.find(params[:userId])
  end

  def update_user
    player = Player.find(params[:playerId])
    player.update(user_id: params[:userId] )
    player.save
    render plain: "OK"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
      @users = User.all()
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :team_id, :user_id, :is_captain, :is_vice_captain)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :player_name %>
  </div>

  <div class="field">

    <% if(!@player.team.nil?)%>
      <%= form.label :team_name %>
      <%= form.label @player.team.name %>
      <%= form.hidden_field :team_id, id: :player_team_id  %>
    <%else%>
      <%= form.label :team_id %>
      <%= form.text_field :team_id, id: :player_team_id  %>
      <%end%>
  </div>

  <div class="field" style="display:none">
    <%= form.label :user_id %>
    <%= collection_select(:player, :user_id, User.all, :id, :name, prompt: true )%>
  </div>

  <div class="field">
    <%= form.label :is_captain %>
    <%= form.check_box :is_captain, id: :player_is_captain %>
  </div>

  <div class="field">
    <%= form.label :is_vice_captain %>
    <%= form.check_box :is_vice_captain, id: :player_is_vice_captain %>
  </div>

  <div class="actions" style="display:none">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.id %></td>
        <td><%= player.name %></td>
        <td><%= player.team.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Team:</strong>
  <%= @player.team.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @player.user.name %>
</p>

<p>
  <strong>Is captain:</strong>
  <%= @player.is_captain %>
</p>

<p>
  <strong>Is vice captain:</strong>
  <%= @player.is_vice_captain %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/players/user.html.erb
<p id="notice"><%= notice %></p>

<h1>Players of <%=@user.name%></h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Team</th>
      <th>Score</th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>

        <td><%= link_to player.id , "/player_scores/" + player.player.id.to_s %></td>
        <td><%= player.player.name + " " %><% if(player.is_captain) %>(C)<%end%> <% if(player.is_vice_captain) %>(VC)<%end%></td>
        <td><%= player.player.team.name %></td>
        <% if(player.is_captain) %>
        <td><%= player.player.player_scores.sum(:total) * 2 %></td>
        <% elsif(player.is_vice_captain) %>
        <% if((@user.id == 39) && (player.player.id == 863)) %>
          <td><%= (player.player.player_scores.where("match_id < ?", 14759).sum(:total)) + (player.player.player_scores.where("match_id >= ?", 14759).sum(:total) * 1.5) %></td>
        <% elsif(@user.id == 50) && (player.player.id == 119) %>
          <td><%= (player.player.player_scores.where("match_id <?", 14759).sum(:total)) + (player.player.player_scores.where("match_id >= ?", 14759).sum(:total) * 1.5) %></td>
        <% else %>
          <td><%= player.player.player_scores.sum(:total) * 1.5 %></td>
        <% end %>
        <%else%>
        <td><%= player.player.player_scores.sum(:total) %></td>
        <%end%>
        <!-- <td><%= link_to 'Edit', edit_player_path(player) %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>